apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: auth-service
data:
  RABBITMQ_DEFAULT_VHOST: auth_vhost
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: auth-service
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: auth_user
  RABBITMQ_DEFAULT_PASS: changeme_local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: auth-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672